#cloud-config

users:
- name: aurion
  uid: 990105

package_update: true
package_upgrade: true
packages:
  - python3.12
  - python3.12-venv
  - curl
  - git
  - build-essential

write_files:
  - path: /opt/target/requirements.txt
    permissions: 0755
    owner: aurion
    content: |
      ${c_requirement_txt}

  - path: /opt/target/exposer.py
    permissions: 0755
    owner: aurion
    content: |
      ${c_application_exposer}

runcmd:
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - export PATH="/root/.cargo/bin:$PATH"
  - python3 -m venv /opt/target/venv
  - /opt/target/venv/bin/python -m pip install --upgrade pip
  - cd /opt/target/
  - source venv/bin/activate
  - uv pip install -r requirements.txt
  - nohup /opt/target/venv/bin/uvicorn agent:app --host 0.0.0.0 --port 9999 --workers 1 --no-server-header --no-date-header &

final_message: "Probe has been provision. The application included exposer (port:9999) in the background"
